set "QUARTUS_INSTALL_PATH=C:\altera_pro\25.1"
set "QUARTUS_ROOTDIR=%QUARTUS_INSTALL_PATH%\quartus\bin64"
set "QSYS_ROOTDIR=%QUARTUS_INSTALL_PATH%\qsys\bin"
set "QUESTA_ROOTDIR=%QUARTUS_INSTALL_PATH%\questa_fse\win64"
set "NIOS_ROOTDIR=%QUARTUS_INSTALL_PATH%\niosv\bin\"

set "PATH=%QUARTUS_ROOTDIR%;%QSYS_ROOTDIR%;%QUESTA_ROOTDIR%;%NIOS_ROOTDIR%;%PATH%"